enum WeatherType {
    DAILY = 'weather/forecast?',
    HOURLY = 'weather/hourly?',
    NOW = 'weather/now?',
    GATHER = '/weather?',
    AIR = '/air/now?'
}

const WeatherIcon = {
    100: 'icon-tianqi-qing',
    101: 'icon-tianqi-duoyun',
    102: 'icon-tianqi-duoyun',
    103: 'icon-tianqi-duoyun',
    104: 'icon-tianqi-yin',
    200: 'icon-tianqi-fengxiang',
    201: 'icon-tianqi-fengxiang',
    202: 'icon-tianqi-fengxiang',
    203: 'icon-tianqi-fengxiang',
    204: 'icon-tianqi-fengxiang',
    205: 'icon-tianqi-fengxiang',
    206: 'icon-tianqi-fengxiang',
    207: 'icon-tianqi-fengxiang',
    208: 'icon-tianqi-fengxiang',
    209: 'icon-tianqi-fengxiang',
    210: 'icon-tianqi-fengxiang',
    211: 'icon-tianqi-fengxiang',
    212: 'icon-tianqi-fengxiang',
    213: 'icon-tianqi-fengxiang',
    300: 'icon-tianqi-zhenyu',
    301: 'icon-tianqi-zhenyu',
    302: 'icon-tianqi-leizhenyu',
    303: 'icon-tianqi-leizhenyu',
    304: 'icon-tianqi-leiyubingbao',
    305: 'icon-tianqi-yu',
    306: 'icon-tianqi-zhongyu',
    307: 'icon-tianqi-dayu',
    308: 'icon-tianqi-dabaoyu',
    309: 'icon-tianqi-yu',
    310: 'icon-tianqi-baoyu',
    311: 'icon-tianqi-dabaoyu',
    312: 'icon-tianqi-dayuzhuantedabaoyu',
    313: 'icon-tianqi-dongyu',
    314: 'icon-tianqi-xiaoyuzhuanzhongyu',
    315: 'icon-tianqi-zhongyuzhuandayu',
    316: 'icon-tianqi-dayuzhuanbaoyu',
    317: 'icon-tianqi-baoyuzhuandabaoyu',
    318: 'icon-tianqi-dayuzhuantedabaoyu',
    399: 'icon-tianqi-yu',
    400: 'icon-tianqi-xiaoxue',
    401: 'icon-tianqi-zhongxue',
    402: 'icon-tianqi-daxue',
    403: 'icon-tianqi-baoxue',
    404: 'icon-tianqi-yujiaxue',
    405: 'icon-tianqi-yujiaxue',
    406: 'icon-tianqi-yujiaxue',
    407: 'icon-tianqi-zhenxue',
    408: 'icon-tianqi-xiaoxuezhuanzhongxue',
    409: 'icon-tianqi-zhongxuezhuandaxue',
    410: 'icon-tianqi-daxuezhuanbaoxue',
    499: 'icon-tianqi-xue',
    500: 'icon-tianqi-wu',
    501: 'icon-tianqi-wu',
    502: 'icon-tianqi-wumai',
    503: 'icon-tianqi-yangsha',
    504: 'icon-tianqi-fuchen',
    507: 'icon-tianqi-shachenbao',
    508: 'icon-tianqi-tedashachenbao',
    509: 'icon-tianqi-wu',
    510: 'icon-tianqi-wu',
    511: 'icon-tianqi-wumai',
    512: 'icon-tianqi-wumai',
    513: 'icon-tianqi-wumai',
    514: 'icon-tianqi-wu',
    515: 'icon-tianqi-wu',
    900: 'icon-tianqi-qing',
    901: 'icon-cold',
    999: 'icon-unknow'
};

const Season = {
    1: 'spring',
    2: 'spring',
    3: 'spring',
    4: 'summer',
    5: 'summer',
    6: 'summer',
    7: 'autumn',
    8: 'autumn',
    9: 'autumn',
    10: 'winter',
    11: 'winter',
    12: 'winter'
};

export { WeatherType, WeatherIcon, Season };
